{{- if and .Values.alertmanager.enabled (and (empty .Values.alertmanager.configMapOverrideName) (empty .Values.alertmanager.configFromSecret)) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "prometheus.alertmanager.labels" . | nindent 4 }}
  name: {{ template "prometheus.alertmanager.fullname" . }}
data:
  custom-template.tmpl: {{ toYaml (index .Values.alertmanagerFiles "custom-template.tmpl") | indent 4 }}
  alertmanager.yml: |
{{ toYaml (index .Values.alertmanagerFiles "alertmanager.yml") | default "{}" | indent 4 }}
{{- end -}}
