{{- if .Values.server.envSecrets }}
{{- range $secretName, $secrets := .Values.server.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    app: {{ template "drone.name" $ }}
    chart: "{{ $.Chart.Name }}-{{ $.Chart.Version }}"
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
type: Opaque
data:
  {{- range $key, $value := $secrets }}
  {{ $key }}: {{ $value | toString | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
